//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crypto.Desktop.Cnsl.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("crypto.Desktop.Cnsl.Recources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added directory {0} to vault..
        /// </summary>
        internal static string AddCommandAsync_AddDirectory_Added_directory__0__to_vault {
            get {
                return ResourceManager.GetString("AddCommandAsync_AddDirectory_Added_directory__0__to_vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with file {0}: {1}.
        /// </summary>
        internal static string AddCommandAsync_AddDirectory_Error_with_file__0____1_ {
            get {
                return ResourceManager.GetString("AddCommandAsync_AddDirectory_Error_with_file__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added file {0} to vault..
        /// </summary>
        internal static string AddCommandAsync_Run_Added_file__0__to_vault {
            get {
                return ResourceManager.GetString("AddCommandAsync_Run_Added_file__0__to_vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument was not recognized..
        /// </summary>
        internal static string CommandLineArgumentParser_ParseConfig_Argument_was_not_recognized {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ParseConfig_Argument_was_not_recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments given..
        /// </summary>
        internal static string CommandLineArgumentParser_ParseConfig_No_arguments_given {
            get {
                return ResourceManager.GetString("CommandLineArgumentParser_ParseConfig_No_arguments_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted file {0}..
        /// </summary>
        internal static string DeleteCommand_Run_Deleted_file_ {
            get {
                return ResourceManager.GetString("DeleteCommand_Run_Deleted_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error locking file {0}: {1}.
        /// </summary>
        internal static string LockCommand_LockAllFiles_Error_locking_file__0____1_ {
            get {
                return ResourceManager.GetString("LockCommand_LockAllFiles_Error_locking_file__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating file .
        /// </summary>
        internal static string LockCommand_LockAllFiles_Updating_file_ {
            get {
                return ResourceManager.GetString("LockCommand_LockAllFiles_Updating_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked all files in Vault..
        /// </summary>
        internal static string LockCommand_Run_Locked_all_files_in_Vault_ {
            get {
                return ResourceManager.GetString("LockCommand_Run_Locked_all_files_in_Vault_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking files....
        /// </summary>
        internal static string LockCommand_Run_Locking_files___ {
            get {
                return ResourceManager.GetString("LockCommand_Run_Locking_files___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new path given..
        /// </summary>
        internal static string MoveCommand_MoveCommand_No_new_path_given {
            get {
                return ResourceManager.GetString("MoveCommand_MoveCommand_No_new_path_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File moved to .
        /// </summary>
        internal static string MoveCommand_Run_File_moved_to_ {
            get {
                return ResourceManager.GetString("MoveCommand_Run_File_moved_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created vault {0} as {1}.
        /// </summary>
        internal static string NewCommandAsync_Run_Created_vault__0__as__1__ {
            get {
                return ResourceManager.GetString("NewCommandAsync_Run_Created_vault__0__as__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory with the vault name is not empty..
        /// </summary>
        internal static string NewCommandAsync_Run_The_directory_vault_is_not_empty {
            get {
                return ResourceManager.GetString("NewCommandAsync_Run_The_directory_vault_is_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password: .
        /// </summary>
        internal static string PasswordPrompt_PromptPassword_Enter_Password__ {
            get {
                return ResourceManager.GetString("PasswordPrompt_PromptPassword_Enter_Password__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password: .
        /// </summary>
        internal static string PasswordPrompt_PromptPasswordWithConfirmation_Confirm_Password__ {
            get {
                return ResourceManager.GetString("PasswordPrompt_PromptPasswordWithConfirmation_Confirm_Password__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password didn&apos;t match up..
        /// </summary>
        internal static string PasswordPrompt_PromptPasswordWithConfirmation_Password_didn_t_match_up {
            get {
                return ResourceManager.GetString("PasswordPrompt_PromptPasswordWithConfirmation_Password_didn_t_match_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No console arguments given..
        /// </summary>
        internal static string Program_Main_No_console_arguments_given {
            get {
                return ResourceManager.GetString("Program_Main_No_console_arguments_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong: .
        /// </summary>
        internal static string Program_Main_Something_went_wrong__ {
            get {
                return ResourceManager.GetString("Program_Main_Something_went_wrong__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Failed: {1}.
        /// </summary>
        internal static string ProgressBar_PrintProgressBar__0__Failed___1_ {
            get {
                return ResourceManager.GetString("ProgressBar_PrintProgressBar__0__Failed___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0}/{1}.
        /// </summary>
        internal static string ProgressBar_PrintProgressBar_Progress___0___1_ {
            get {
                return ResourceManager.GetString("ProgressBar_PrintProgressBar_Progress___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new name given..
        /// </summary>
        internal static string RenameCommand_RenameCommand_No_new_name_given {
            get {
                return ResourceManager.GetString("RenameCommand_RenameCommand_No_new_name_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No path to file given..
        /// </summary>
        internal static string RenameCommand_RenameCommand_No_path_to_file_given {
            get {
                return ResourceManager.GetString("RenameCommand_RenameCommand_No_path_to_file_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No path to vault given..
        /// </summary>
        internal static string RenameCommand_RenameCommand_No_path_to_vault_given {
            get {
                return ResourceManager.GetString("RenameCommand_RenameCommand_No_path_to_vault_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File renamed to .
        /// </summary>
        internal static string RenameCommand_Run_File_renamed_to_ {
            get {
                return ResourceManager.GetString("RenameCommand_Run_File_renamed_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to rename wasn&apos;t found..
        /// </summary>
        internal static string RenameCommand_Run_The_file_to_rename_wasn_t_found {
            get {
                return ResourceManager.GetString("RenameCommand_Run_The_file_to_rename_wasn_t_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error unlocking file {0}: {1}.
        /// </summary>
        internal static string UnlockCommandAsync_ExtractAllFiles_Error_unlocking_file__0____1_ {
            get {
                return ResourceManager.GetString("UnlockCommandAsync_ExtractAllFiles_Error_unlocking_file__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} has been altered, be careful with this file..
        /// </summary>
        internal static string UnlockCommandAsync_Run_File_has_been_altered {
            get {
                return ResourceManager.GetString("UnlockCommandAsync_Run_File_has_been_altered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault unlocked..
        /// </summary>
        internal static string UnlockCommandAsync_Run_Vault_unlocked_ {
            get {
                return ResourceManager.GetString("UnlockCommandAsync_Run_Vault_unlocked_", resourceCulture);
            }
        }
    }
}
